#application.yml

#애플리케이션 이름
spring:
  application:
    name: web

#DB 스키마 자동 관리 전략
  jpa:
    hibernate:
      ddl-auto: update #운영(prod)에서는 보통 validate 또는 none
    properties:
      hibernate:
        format_sql: false #SQL 줄바꿈/정렬
        highlight_sql: false #콘솔 색상 강조
        use_sql_comments: false #JPQL → SQL 주석 표시
  profiles: #현재 실행 중인 프로필
    include: secret #항상 같이 로드할 프로필
    active: dev


  output:
    ansi:
      enabled: always #Spring 로그  컬러 켬

server:
  port: 8080

#jwt:
#  access-expiration: 3600 # 1시간
#  refresh-expiration: 604800 # 7일

logging:
  output:
    ansi:
      enabled: always

---
spring:
  config:
    activate:
      on-profile: prod

  h2:
    console:
      enabled: true
      path: /h2-console