# application-secret.yml (수정본)
spring:
  mail:
    username: 'uswbookverify@gmail.com'
    password: 'vinunguefxdvsdkp'   # ← 공백 제거된 실제 앱 비밀번호(예시)

custom:
  jwt:
    secret-key: '!@@!$!@#@!#!@#ahsdjqkjbjxkhkhquwd*!@&%(!@#*1238717269dshg12786312jghajkqd'
    access-token-expire-seconds: 900
    refresh-token-expire-seconds: 604800

  prod:
    db:
      password: 'subook0000'
    redis:
      password: 'subook1234'

  stg:
    db:
      password: 'subook1234'
    redis:
      password: 'subook1234'

