# 실제 배포중인 운영 서버에 대한 설정
#application-prod.yml
spring:
  data:
    redis:
      host: localhost
      password: ${custom.prod.redis.password}
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/spring_crud?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver